### PR TITLE
Add / remove / update headshots

### PR DESCRIPTION
**Pull request by jrubenoff**
- Add Victor. (@vlymar, I grabbed this from your Slack avatar. LMK whether this is OK for the company to use!)
- Remove former employees
- Update my headshot

### CODE REVIEW

**Comment by ajb** [comment]
Former employees should not be removed from this repo, since their avatars on i.e. old blogposts would disappear.

**Comment by ajb** [comment]
Also, these should be 250x250 if at all possible..

**Comment by jrubenoff** [comment]
OK, perhaps @vlymar can upload his own headshot at the desired resolution. I have no new pictures of myself at a greater resolution than 192x192.

**Comment by ajb** [comment]
K. This is formally an [onboarding task](https://github.com/dobtco/dobt/blob/master/ONBOARDING.md), so Victor, please do so when you have a moment.

**Pull request closed without merging**
